PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore

  Fasterer:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore

PrePush:
  RSpec:
    enabled: true
    on_warn: fail