
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ms_development

test:
  <<: *default
  database: ms_test

production:
  <<: *default
  database: ms_production
  username: postgres
  password:
