
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: 6975

development:
  <<: *default
  database: health_hub_development

test:
  <<: *default
  database: health_hub_test

production:
  <<: *default
  database: health_hub_production
